#!/usr/bin/env python3
r"""
Assemble the Five-System Comparative Analysis section for BOTH experiments
(exp1_five and exp2_five) into a single drop-in LaTeX section.

Why two experiments, one section:
- exp1_five (Core-15 Feynman) and exp2_five (Feynman 10-domain suite) are
  DIFFERENT equation suites with different sample sizes -- per the auto-
  generated captions themselves ("a separate table from tab:five_systems_full
  -- different equation suite and sample sizes, not another view of the same
  data"). They should not be merged into one table; they belong as two
  clearly-labeled subsections under the same \subsection.
- Each experiment already has its own auto-generated table fragments
  (summary, extrapolation-by-regime, interpolation-performance, and
  Mann-Whitney/Cohen's-d stat-test prose) sitting in separate .tex files.
  This script just reads those fragments off disk and assembles them into
  one coherent, paste-ready section with connective prose and subsection
  headers -- it does not recompute any numbers.

Inputs (auto-generated by tables/generate_tables.py, read verbatim):
  exp1_five:  five_system.tex, five_system_extrapolation.tex,
              five_system_performance.tex, five_system_stat_tests.tex
  exp2_five:  five_system_exp2five.tex, five_system_exp2five_extrapolation.tex,
              five_system_exp2five_performance.tex,
              five_system_exp2five_stat_tests.tex

Output:
  five_system_comparative_analysis_section.tex -- full replacement for
  jmlr_paper_main.tex's "Five-System Comparative Analysis" subsection.

Usage:
    python3 assemble_five_system_section.py <dir containing the 8 input files>
"""
import os
import re
import sys


EXP1_FILES = [
    "five_system.tex",
    "five_system_extrapolation.tex",
    "five_system_performance.tex",
    "five_system_stat_tests.tex",
]

EXP2_FILES = [
    "five_system_exp2five.tex",
    "five_system_exp2five_extrapolation.tex",
    "five_system_exp2five_performance.tex",
    "five_system_exp2five_stat_tests.tex",
]


def strip_autogen_header(text):
    """Drop the '% Auto-generated ... DO NOT EDIT MANUALLY' boilerplate header,
    but keep any trailing '% Source: ...' provenance comment at the end."""
    lines = text.splitlines()
    out = []
    skipping_header = True
    for line in lines:
        if skipping_header:
            if line.strip().startswith("%") or line.strip() == "":
                continue
            skipping_header = False
        out.append(line)
    return "\n".join(out).strip("\n")


def load_fragment(directory, filename):
    path = os.path.join(directory, filename)
    with open(path) as f:
        raw = f.read()
    return strip_autogen_header(raw)


def has_real_data(fragment_text):
    """Crude check: does this fragment contain anything beyond a
    '% NO DATA' placeholder comment?"""
    stripped = "\n".join(
        l for l in fragment_text.splitlines() if not l.strip().startswith("%")
    ).strip()
    return bool(stripped)


# ---------------------------------------------------------------------------
# Winner bolding
# ---------------------------------------------------------------------------
# For every table, we bold the best value per genuine performance column,
# within whatever grouping makes systems actually comparable in that row
# ("case"): either the whole table (one row per system) or sub-groups sharing
# a key like "Regime" (near/medium/far). Columns that are themselves flagged
# as unreliable (the degenerate Std/95% CI columns -- see the data-quality
# notes below) are deliberately left un-bolded: declaring a "winner" in a
# column we already know is computed wrong would just dress up a bug as a
# result.

MISSING_TOKENS = {"---", "--", "-", ""}


def _parse_float(cell):
    cell = cell.strip()
    if cell in MISSING_TOKENS:
        return None
    try:
        return float(cell)
    except ValueError:
        return None


def _split_row(line):
    """Split a data row 'a & b & c \\\\' into cells (list[str]) plus the
    original trailing row-terminator ('\\\\' or '\\\\[2pt]' etc, if present)."""
    stripped = line.rstrip("\n")
    m = re.search(r"(\\\\(?:\[[^\]]*\])?)\s*$", stripped)
    terminator = m.group(1) if m else ""
    body = stripped[: m.start()] if m else stripped
    cells = [c.strip() for c in body.split("&")]
    return cells, terminator


def _is_data_row(line):
    s = line.strip()
    if not s or s.startswith("%"):
        return False
    if s.startswith(("\\toprule", "\\midrule", "\\bottomrule", "\\multicolumn",
                      "\\begin", "\\end", "\\centering", "\\caption", "\\label",
                      "\\small", "\\scriptsize", "\\setlength", "\\textbf{System}")):
        return False
    return "&" in s


def bold_winners(tex_table, compare_cols, group_col=None):
    r"""
    tex_table: full LaTeX table source (a \begin{table}...\end{table} block).
    compare_cols: list of (col_index, direction) where direction is 'max' or
      'min', col_index is 0-based into the split row cells.
    group_col: 0-based cell index to group rows by before picking a winner
      (e.g. the 'Regime' column). None = whole table is one group.

    A block boundary (\midrule appearing again after the header, or a
    \multicolumn separator row) starts a fresh group even under the same
    group_col value, since rows on either side of such a divider (e.g. the
    'Systems Without Extrapolation Testing' block) are not meant to be
    compared against each other.
    """
    lines = tex_table.splitlines()
    out_lines = []

    # Locate header end: first \midrule after \toprule.
    header_done = False
    seen_toprule = False
    block_rows = []  # list of (line_index_in_out, cells, terminator)
    pending_block_start = None

    def flush_block():
        nonlocal block_rows
        if not block_rows:
            return
        if group_col is None:
            groups = {None: block_rows}
        else:
            groups = {}
            for item in block_rows:
                key = item[1][group_col] if group_col < len(item[1]) else None
                groups.setdefault(key, []).append(item)
        for key, rows in groups.items():
            for col_idx, direction in compare_cols:
                values = []
                for out_idx, cells, term in rows:
                    if col_idx >= len(cells):
                        continue
                    v = _parse_float(cells[col_idx])
                    if v is not None:
                        values.append((out_idx, v))
                if len(values) < 2:
                    continue  # nothing to compare -> no "winner" to mark
                best = max(v for _, v in values) if direction == "max" else min(v for _, v in values)
                tol = 1e-9 * max(1.0, abs(best))
                for out_idx, v in values:
                    if abs(v - best) <= tol:
                        cells = block_rows_by_idx[out_idx][1]
                        if not cells[col_idx].strip().startswith("\\textbf"):
                            cells[col_idx] = r"\textbf{" + cells[col_idx].strip() + "}"
        block_rows = []

    block_rows_by_idx = {}

    for line in lines:
        s = line.strip()
        if s.startswith("\\toprule"):
            seen_toprule = True
            out_lines.append(line)
            continue
        if s.startswith("\\midrule"):
            if seen_toprule and not header_done:
                header_done = True  # this midrule ends the header
                out_lines.append(line)
                continue
            else:
                flush_block()
                out_lines.append(line)
                continue
        if s.startswith("\\bottomrule"):
            flush_block()
            out_lines.append(line)
            continue
        if s.startswith("\\multicolumn"):
            flush_block()
            out_lines.append(line)
            continue
        if header_done and _is_data_row(line):
            cells, term = _split_row(line)
            out_idx = len(out_lines)
            out_lines.append(None)  # placeholder, filled in after flush
            block_rows_by_idx[out_idx] = [out_idx, cells, term]
            block_rows.append((out_idx, cells, term))
            continue
        out_lines.append(line)

    flush_block()

    # Render placeholder rows back into text.
    for out_idx, entry in block_rows_by_idx.items():
        _, cells, term = entry
        rendered = " & ".join(cells)
        if term:
            rendered = rendered + " " + term
        out_lines[out_idx] = rendered

    return "\n".join(out_lines)


def assemble(directory):
    exp1_frags = {f: load_fragment(directory, f) for f in EXP1_FILES}
    exp2_frags = {f: load_fragment(directory, f) for f in EXP2_FILES}

    # --- Apply winner-bolding to each table -------------------------------
    # Columns compared are genuine performance metrics only; the degenerate
    # Std / 95% CI columns (see data-quality notes below) are intentionally
    # left un-bolded.
    LOWER = "min"
    HIGHER = "max"

    exp1_frags["five_system.tex"] = bold_winners(
        exp1_frags["five_system.tex"],
        compare_cols=[(2, LOWER), (3, LOWER), (4, HIGHER)],  # Extrap Median/Mean, Train R2 Mean
    )
    exp1_frags["five_system_performance.tex"] = bold_winners(
        exp1_frags["five_system_performance.tex"],
        compare_cols=[(2, HIGHER), (4, LOWER)],  # Train R2 Mean, Train RMSE Mean
    )
    exp1_frags["five_system_extrapolation.tex"] = bold_winners(
        exp1_frags["five_system_extrapolation.tex"],
        compare_cols=[(3, HIGHER), (4, LOWER)],  # Extrap R2 Mean, Extrap RMSE Mean
        group_col=1,  # Regime: near / medium / far
    )
    exp2_frags["five_system_exp2five.tex"] = bold_winners(
        exp2_frags["five_system_exp2five.tex"],
        compare_cols=[(2, LOWER), (3, LOWER), (4, HIGHER)],
    )
    exp2_frags["five_system_exp2five_performance.tex"] = bold_winners(
        exp2_frags["five_system_exp2five_performance.tex"],
        compare_cols=[(2, HIGHER)],  # Train R2 Mean (no RMSE column in this table)
    )
    exp2_frags["five_system_exp2five_extrapolation.tex"] = bold_winners(
        exp2_frags["five_system_exp2five_extrapolation.tex"],
        compare_cols=[(2, LOWER), (3, LOWER)],
    )

    parts = []

    parts.append(r"""\subsection{Five-System Comparative Analysis}\label{subsec:fivesystem-comparative-analysis-feynman-}
\label{sec:five_systems}

We compare five system configurations (Hybrid v50\_2, Neural Network, Pure
LLM, System 2 Symbolic, System 3 LLM+Fallback) across two independent
benchmark suites. \textbf{exp1\_five} uses the Core-15 Feynman equation set;
\textbf{exp2\_five} uses a separate Feynman 10-domain suite. The two suites
have different equations and different per-system sample sizes, so their
results are reported as two separate experiments below rather than pooled
into a single table.

Within each table below, and within each regime sub-group where applicable
(near/medium/far), we \textbf{bold} the winning (best) value among the five
systems for each genuine performance column (extrapolation error, $R^2$,
RMSE). The Std and 95\,\% CI columns are \emph{not} used to declare a winner,
since their underlying computation is already flagged as unreliable (see the
data-quality notes at the end of this section) -- bolding a value there would
dress up a bug as a result. A column is left unbolded wherever fewer than two
systems have a valid (non-\texttt{---}) value to compare.""")

    # ---------------- Experiment 1 ----------------
    parts.append(r"""\subsubsection{Experiment 1: Core-15 Feynman (exp1\_five)}\label{subsubsec:five-system-exp1}""")
    parts.append(r"""Table~\ref{tab:five_systems_full} summarizes extrapolation error
and interpolation $R^2$ for all five systems on Core-15. Tables~\ref{tab:five_systems_performance}
and \ref{tab:five_systems_extrapolation} break interpolation and extrapolation
performance down further; Appendix~\ref{app:statistical_tests} (below) reports
the corresponding Mann-Whitney test and effect-size calculation.""")

    parts.append(exp1_frags["five_system.tex"])
    parts.append(exp1_frags["five_system_performance.tex"])
    parts.append(exp1_frags["five_system_extrapolation.tex"])

    # ---------------- Experiment 2 ----------------
    parts.append(r"""\subsubsection{Experiment 2: Feynman 10-Domain Suite (exp2\_five)}\label{subsubsec:five-system-exp2}""")
    parts.append(r"""Table~\ref{tab:five_systems_full_exp2five} reports the same
comparison on the exp2\_five suite. Tables~\ref{tab:five_systems_performance_exp2five}
and \ref{tab:five_systems_extrapolation_exp2five} give the interpolation and
extrapolation breakdowns for this suite.""")

    parts.append(exp2_frags["five_system_exp2five.tex"])
    parts.append(exp2_frags["five_system_exp2five_performance.tex"])
    parts.append(exp2_frags["five_system_exp2five_extrapolation.tex"])

    # ---------------- Appendix: statistical test details for both ----------------
    appendix_parts = []
    appendix_parts.append(r"""\section{Statistical Test Details}
\label{app:statistical_tests}""")

    appendix_parts.append(r"""\subsection*{Experiment 1 (exp1\_five, Core-15)}""")
    appendix_parts.append(exp1_frags["five_system_stat_tests.tex"])

    appendix_parts.append(r"""\subsection*{Experiment 2 (exp2\_five, 10-domain suite)}""")
    if has_real_data(exp2_frags["five_system_exp2five_stat_tests.tex"]):
        appendix_parts.append(exp2_frags["five_system_exp2five_stat_tests.tex"])
    else:
        appendix_parts.append(
            r"\textit{No statistical test is reported for exp2\_five: "
            r"the generator requires both Hybrid v50\_2 and Neural Network "
            r"to have at least one successful, finite extrapolation-error "
            r"measurement each, and exp2\_five currently has zero for both "
            r"(see Tables~\ref{tab:five_systems_full_exp2five} and "
            r"\ref{tab:five_systems_extrapolation_exp2five}).}"
        )

    section_text = "\n\n".join(parts) + "\n\n" + "\n\n".join(appendix_parts) + "\n"
    return section_text


def main():
    directory = sys.argv[1] if len(sys.argv) > 1 else "."
    section_text = assemble(directory)

    print("=" * 78)
    print("ASSEMBLED FIVE-SYSTEM COMPARATIVE ANALYSIS SECTION (both experiments)")
    print("=" * 78)
    print()
    print(section_text)

    # --- Data-quality flags worth the authors' attention before this ships ---
    print("=" * 78)
    print("DATA-QUALITY FLAGS (not fixed here -- for author review)")
    print("=" * 78)
    print("- tab:five_systems_full (exp1_five): the '95% CI' column is degenerate")
    print("  ([X, X], i.e. lower==upper==mean) for every row with data. That is a")
    print("  sign the CI computation isn't actually running (e.g. Std column here")
    print("  is Train R^2 std, not extrapolation-error std, so CI collapses).")
    print("- tab:five_systems_extrapolation / tab:five_systems_performance (exp1_five):")
    print("  Pure LLM RMSE and System 2 RMSE values are astronomically large")
    print("  (1e15-1e26 range), and Hybrid v50_2 medium-regime RMSE is ~1.17e25 --")
    print("  almost certainly unclipped divide-by-near-zero blowups, not real errors.")
    print("- tab:five_systems_full_exp2five: n=0 for every system in the main")
    print("  extrapolation columns (routed entirely to the 'Without Extrapolation")
    print("  Testing' block) -- exp2_five currently has no extrapolation data at all,")
    print("  only interpolation (Train R^2). The stat-test subsection is empty for")
    print("  the same reason.")
    print("- repro_macros.tex's \\nnExtrapStd (0.1) does not match five_system.tex's")
    print("  own Neural Network Std column (0.0565) for the same exp1_five run --")
    print("  another sign the CI/std pipeline for this table is not reliable yet.")
    print("- With winners now bolded on the genuine performance columns: in")
    print("  tab:five_systems_extrapolation's 'medium' regime, System 2 Symbolic")
    print("  wins on Extrap R2 Mean (0.534) over Hybrid v50_2 (-0.749) -- i.e. the")
    print("  proposed system does NOT win every case once bolding is done honestly")
    print("  off the existing (buggy) numbers. Worth a second look before publishing.")
    print()
    print("None of the above numbers were altered by this script -- it only")
    print("assembles the existing auto-generated fragments. These look like the")
    print("same class of bug as Issue 4/Issue 9 and likely warrant their own")
    print("tracked issues before this section is presented as final.")

    out_path = "five_system_comparative_analysis_section.tex"
    with open(out_path, "w") as f:
        f.write(section_text)
    print()
    print(f"[Assembled section written to {out_path}]")

    return section_text


if __name__ == "__main__":
    main()
