#!/usr/bin/env python3
"""
generate_tables.py — Auto-generate LaTeX tables from JSON results

Reads patched JSON outputs and writes .tex table fragments to paper/tables/.
These are \\input{}-ed by the main paper so NO manual numbers appear in the LaTeX source.

Tables generated:
  - defi_main.tex       (Table 1 — §10.2)
  - defi_tiers.tex      (Table 2 — §10.3)
  - ablation.tex        (Table 5 — §10.6)
  - nguyen12.tex        (Table 7 — §10.8)
  - instability.tex     (Table 8 — §10.9)
"""
import json
import os
import sys
from datetime import datetime
from pathlib import Path

ROOT       = Path(__file__).parent.parent
PATCHED    = ROOT / "hypatiax" / "data" / "patched"
RESULTS    = ROOT / "hypatiax" / "data" / "results"
TABLES_DIR = ROOT / "paper" / "tables"

TABLES_DIR.mkdir(parents=True, exist_ok=True)

GENERATED = 0

def load_best(subdir, glob):
    for base in [PATCHED, RESULTS]:
        d = base / subdir
        if not d.exists():
            continue
        candidates = sorted(d.glob(glob), key=os.path.getmtime, reverse=True)
        if candidates:
            try:
                return json.loads(candidates[0].read_text()), candidates[0]
            except Exception:
                continue
    return None, None

def write_table(name, content):
    global GENERATED
    out = TABLES_DIR / name
    out.write_text(content)
    print(f"  ✅ {name}")
    GENERATED += 1

def header_comment(src_file):
    return (
        f"% Auto-generated by scripts/generate_tables.py\n"
        f"% Source: {src_file}\n"
        f"% Date:   {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"% DO NOT EDIT MANUALLY — re-run 'make tables' to regenerate\n\n"
    )

# ── Table: DeFi main results (§10.2) ──────────────────────────────────────────
def gen_defi_main():
    data, src = load_best("defi", "benchmark_results*.json")
    if not data:
        print("  ⚠  defi_main.tex — no data found, writing placeholder")
        write_table("defi_main.tex", "% No DeFi results yet\n")
        return

    acc      = data.get("accuracy", data.get("success_rate", data.get("discovery_rate", 0)))
    total    = data.get("total_cases", data.get("n_cases", "?"))
    successes= data.get("successes", data.get("n_success", int(acc * total) if isinstance(total, int) else "?"))
    timing   = data.get("mean_time", data.get("avg_time_s", data.get("runtime_s", "?")))
    r2_mean  = data.get("mean_r2", data.get("avg_r2", "?"))

    tex = header_comment(src) + r"""
\begin{table}[h]
\centering
\caption{HypatiaX DeFi Benchmark Results (v3.0)}
\label{tab:defi_main}
\begin{tabular}{lrr}
\toprule
\textbf{Metric} & \textbf{Value} & \textbf{Notes} \\
\midrule
""" + f"Discovery rate & {acc:.1%} & {successes}/{total} cases \\\\\n"

    if r2_mean != "?":
        tex += f"Mean $R^2$ & {r2_mean:.4f} & across successful discoveries \\\\\n"
    if timing != "?":
        tex += f"Mean runtime & {timing:.1f}s & per case \\\\\n"

    tex += r"""\bottomrule
\end{tabular}
\end{table}
"""
    write_table("defi_main.tex", tex)

# ── Table: DeFi tier breakdown (§10.3) ────────────────────────────────────────
def gen_defi_tiers():
    data, src = load_best("defi", "benchmark_results*.json")
    if not data:
        write_table("defi_tiers.tex", "% No DeFi results yet\n")
        return

    tiers = {
        "Easy":   data.get("easy_cases",   data.get("easy",   {}).get("count", "?")),
        "Medium": data.get("medium_cases", data.get("medium", {}).get("count", "?")),
        "Hard":   data.get("hard_cases",   data.get("hard",   {}).get("count", "?")),
    }
    tier_acc = {
        "Easy":   data.get("easy_accuracy",   data.get("easy",   {}).get("accuracy", "?")),
        "Medium": data.get("medium_accuracy", data.get("medium", {}).get("accuracy", "?")),
        "Hard":   data.get("hard_accuracy",   data.get("hard",   {}).get("accuracy", "?")),
    }

    tex = header_comment(src) + r"""
\begin{table}[h]
\centering
\caption{DeFi Benchmark — Results by Difficulty Tier}
\label{tab:defi_tiers}
\begin{tabular}{lcc}
\toprule
\textbf{Tier} & \textbf{Cases} & \textbf{Discovery Rate} \\
\midrule
"""
    for tier, count in tiers.items():
        acc_str = f"{tier_acc[tier]:.1%}" if isinstance(tier_acc[tier], float) else "---"
        tex += f"{tier} & {count} & {acc_str} \\\\\n"

    tex += r"""\midrule
Total & 74 & ---  \\
\bottomrule
\end{tabular}
\end{table}
"""
    write_table("defi_tiers.tex", tex)

# ── Table: Core-15 ablation (§10.6) ───────────────────────────────────────────
def gen_ablation():
    data, src = load_best("exp1_ablation", "*.json")
    if not data:
        write_table("ablation.tex", "% No ablation results yet\n")
        return

    # Try to extract per-method R2 values
    hypatia_r2 = data.get("hypatiax_far_r2", data.get("far_r2_hypatiax", "?"))
    pysr_r2    = data.get("pysr_far_r2",    data.get("far_r2_pysr", "?"))
    mw_p       = data.get("mw_p", data.get("mann_whitney_p", data.get("p_value", "?")))
    mw_u       = data.get("mw_u", data.get("mann_whitney_u", data.get("u_statistic", "?")))

    tex = header_comment(src) + r"""
\begin{table}[h]
\centering
\caption{Core-15 Ablation: PySR-only vs.\ HypatiaX (far-$R^2$)}
\label{tab:llm_ablation}
\begin{tabular}{lcc}
\toprule
\textbf{System} & \textbf{Mean far-$R^2$} & \textbf{n} \\
\midrule
"""
    hyp_str = f"{hypatia_r2:.4f}" if isinstance(hypatia_r2, float) else "---"
    psr_str = f"{pysr_r2:.4f}"    if isinstance(pysr_r2,    float) else "---"

    tex += f"HypatiaX & {hyp_str} & 15 \\\\\n"
    tex += f"PySR-only & {psr_str} & 15 \\\\\n"

    mw_str = ""
    if isinstance(mw_p, float):
        mw_str = f"$U={mw_u:.1f}$, $p={mw_p:.4f}$ (two-sided)"

    tex += r"""\bottomrule
\end{tabular}
"""
    if mw_str:
        tex += f"\\begin{{tablenotes}}\\item Mann-Whitney: {mw_str}\\end{{tablenotes}}\n"
    tex += r"\end{table}" + "\n"

    write_table("ablation.tex", tex)

# ── Table: Instability summary (§10.9) ────────────────────────────────────────
def gen_instability():
    data, src = load_best("instability", "*.json")
    if not data:
        write_table("instability.tex", "% No instability results yet\n")
        return

    total    = data.get("total_tasks", data.get("n_tasks", 70))
    k_runs   = data.get("k_runs", data.get("n_runs", 30))
    spearman = data.get("spearman_rho", data.get("rho", "?"))
    cv_mean  = data.get("mean_cv", data.get("cv_mean", "?"))

    tex = header_comment(src) + r"""
\begin{table}[h]
\centering
\caption{Instability Analysis: """ + f"{total} tasks, $K={k_runs}$" + r""" runs each}
\label{tab:instability}
\begin{tabular}{lc}
\toprule
\textbf{Metric} & \textbf{Value} \\
\midrule
"""
    tex += f"Total tasks & {total} \\\\\n"
    tex += f"Runs per task ($K$) & {k_runs} \\\\\n"
    if isinstance(spearman, float):
        tex += f"Spearman $\\rho$ & {spearman:.4f} \\\\\n"
    if isinstance(cv_mean, float):
        tex += f"Mean CV & {cv_mean:.4f} \\\\\n"

    tex += r"""\bottomrule
\end{tabular}
\end{table}
"""
    write_table("instability.tex", tex)

# ── Reproducibility macro file ────────────────────────────────────────────────
def gen_repro_macros():
    """Write a LaTeX macro file so numbers can be \repro{defi_accuracy} in text."""
    macros = {}

    data, _ = load_best("defi", "benchmark_results*.json")
    if data:
        acc = data.get("accuracy", data.get("success_rate", 0))
        macros["defiAccuracy"]   = f"{acc:.1%}"
        macros["defiTotalCases"] = str(data.get("total_cases", 74))

    data, _ = load_best("exp1_ablation", "*.json")
    if data:
        mw_p = data.get("mw_p", data.get("mann_whitney_p", ""))
        mw_u = data.get("mw_u", data.get("mann_whitney_u", ""))
        if mw_p:
            macros["coreAblationMWp"] = f"{mw_p:.4f}"
        if mw_u:
            macros["coreAblationMWu"] = f"{mw_u:.1f}"

    lines = [
        "% Auto-generated reproducibility macros",
        "% Usage in paper: \\repoVal{defiAccuracy}",
        f"% Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]
    for key, val in macros.items():
        lines.append(f"\\newcommand{{\\{key}}}{{{val}}}")

    write_table("repro_macros.tex", "\n".join(lines) + "\n")

# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("═" * 55)
    print("  Table Generator — HypatiaX JMLR")
    print("═" * 55)
    print("  Output: paper/tables/\n")

    gen_defi_main()
    gen_defi_tiers()
    gen_ablation()
    gen_instability()
    gen_repro_macros()

    print(f"\n{'═'*55}")
    print(f"  Generated: {GENERATED} table files")
    print(f"{'═'*55}")
    print("""
  To use in LaTeX:
    \\input{tables/defi_main.tex}
    \\input{tables/ablation.tex}
    \\input{tables/repro_macros.tex}
""")

if __name__ == "__main__":
    main()
