#!/usr/bin/env python3
r"""
Issue 17 — runtime.tex / timing_detail.tex Do Not Reproduce From Their Own
Cited Source

Both tab:runtime (runtime.tex) and tab:timing_detail (timing_detail.tex) carry
the header:
    % Auto-generated by tables/generate_tables.py
    % Source: hypatiax/data/results/comparison_results/noise-noiseless/
              noiseless/defi/hypatiax_defi_benchmark_v3_results_seed42.json
    % Date:   2026-08-03 16:01
    % DO NOT EDIT MANUALLY -- re-run 'make tables' to regenerate

...and report:
    Neural MLP:  mean 3.0s / median 2.7s
    HypatiaX:    mean 6.8s / median 1.7s  (2.30x SLOWER mean / 1.64x FASTER median)
    HypatiaX (LLM-routed only, n=68): 1.73x FASTER

This script computes the same statistics directly from the exact file named
as the source (which is the file we have on disk). The result does not match
what's in the paper's tables -- not in absolute magnitude, and not in the
direction of the headline speedup claim. This independently confirms the
finding already reported in table1_audit_old.tex (an earlier, separate audit
pass over a wider pool of seed/variant files), using only the single file
that runtime.tex/timing_detail.tex themselves cite.

Usage:
    python3 recover_issue17_runtime.py hypatiax_defi_benchmark_v3_results_seed42.json
"""
import json
import statistics as stats
import sys


def mean_median(xs):
    return stats.mean(xs), stats.median(xs)


def analyze(path):
    with open(path) as f:
        data = json.load(f)
    assert len(data) == 74, f"Expected 74 tasks, found {len(data)}"

    nn_times = [d["results"]["neural_network"]["time_s"] for d in data]
    llm_times = [d["results"]["pure_llm"]["time_s"] for d in data]
    hybrid_times = [d["results"]["hybrid"]["time_s"] for d in data]

    llm_routed = [d for d in data if d["results"]["hybrid"].get("decision") == "llm"]
    hy_llm_routed_times = [d["results"]["hybrid"]["time_s"] for d in llm_routed]

    nn_mean, nn_med = mean_median(nn_times)
    llm_mean, llm_med = mean_median(llm_times)
    hy_mean, hy_med = mean_median(hybrid_times)
    hyr_mean, hyr_med = mean_median(hy_llm_routed_times)

    return {
        "n": len(data),
        "n_llm_routed": len(llm_routed),
        "nn": (nn_mean, nn_med),
        "llm": (llm_mean, llm_med),
        "hybrid_all": (hy_mean, hy_med),
        "hybrid_llm_routed": (hyr_mean, hyr_med),
    }


REPORTED = {
    "nn": (3.0, 2.7),
    "llm": (11.4, 10.3),
    "hybrid_all": (6.8, 1.7),
    "hybrid_llm_routed_speedup_median": "1.73x FASTER (n=68)",
}


ORIGINAL_TEX_RUNTIME = r"""\begin{table}[t]
\centering
\caption{Wall-clock time per task (seconds). HypatiaX timing includes full LLM
  inference plus any NN retraining cost. Speedups relative to Neural MLP.}
\label{tab:runtime}
\begin{tabular}{lrrrr}
\toprule
\textbf{Method} & \textbf{Mean (s)} & \textbf{Median (s)}
  & \textbf{n} & \textbf{vs.\ NN} \\
\midrule
Pure LLM & 11.4 & 10.3 & 74 & 3.80\texttimes\ slower \\
Neural MLP & 3.0 & 2.7 & 74 & --- (baseline) \\
HypatiaX & 6.8 & 1.7 & 74 & 2.30\texttimes\ slower (mean) / 1.64\texttimes\ faster (median) \\
HypatiaX (LLM-routed only) & --- & --- & 68 & 1.73\texttimes\ faster \\
\bottomrule
\end{tabular}
\end{table}
"""


def generate_corrected_tex(stats_dict):
    nn_mean, nn_med = stats_dict["nn"]
    llm_mean, llm_med = stats_dict["llm"]
    hy_mean, hy_med = stats_dict["hybrid_all"]
    hyr_mean, hyr_med = stats_dict["hybrid_llm_routed"]
    n = stats_dict["n"]
    n_routed = stats_dict["n_llm_routed"]

    llm_vs_nn_mean = llm_mean / nn_mean
    llm_vs_nn_med = llm_med / nn_med
    hy_vs_nn_mean = hy_mean / nn_mean
    hy_vs_nn_med = hy_med / nn_med
    hyr_vs_nn_mean = hyr_mean / nn_mean
    hyr_vs_nn_med = hyr_med / nn_med

    return r"""\begin{table}[t]
\centering
\caption{Wall-clock time per task (seconds), recomputed directly from
  \texttt{hypatiax\_defi\_benchmark\_v3\_results\_seed42.json} (the file this
  table's own header already cites as its source). HypatiaX timing includes
  full LLM inference plus any NN retraining cost. Speedups relative to
  Neural MLP. \textbf{HypatiaX is slower than the Neural MLP baseline in
  every framing below}; no reconstruction of this file supports a "faster"
  claim in either mean or median.}
\label{tab:runtime}
\begin{tabular}{lrrrr}
\toprule
\textbf{Method} & \textbf{Mean (s)} & \textbf{Median (s)}
  & \textbf{n} & \textbf{vs.\ NN} \\
\midrule
Pure LLM & """ + f"{llm_mean:.2f}" + r""" & """ + f"{llm_med:.2f}" + r""" & """ + str(n) + r""" & """ + f"{llm_vs_nn_mean:.2f}" + r"""\texttimes\ slower \\
Neural MLP & """ + f"{nn_mean:.2f}" + r""" & """ + f"{nn_med:.2f}" + r""" & """ + str(n) + r""" & --- (baseline) \\
HypatiaX & """ + f"{hy_mean:.2f}" + r""" & """ + f"{hy_med:.2f}" + r""" & """ + str(n) + r""" & """ + f"{hy_vs_nn_mean:.2f}" + r"""\texttimes\ slower (mean) / """ + f"{hy_vs_nn_med:.2f}" + r"""\texttimes\ slower (median) \\
HypatiaX (LLM-routed only) & """ + f"{hyr_mean:.2f}" + r""" & """ + f"{hyr_med:.2f}" + r""" & """ + str(n_routed) + r""" & """ + f"{hyr_vs_nn_mean:.2f}" + r"""\texttimes\ slower \\
\bottomrule
\end{tabular}
\end{table}
"""


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "hypatiax_defi_benchmark_v3_results_seed42.json"
    s = analyze(path)

    print("=== Recomputed directly from the file runtime.tex/timing_detail.tex cite as their source ===")
    print(f"  n = {s['n']}, n LLM-routed = {s['n_llm_routed']}")
    print(f"  Pure LLM   : mean={s['llm'][0]:.3f}s  median={s['llm'][1]:.3f}s")
    print(f"  Neural MLP : mean={s['nn'][0]:.3f}s  median={s['nn'][1]:.3f}s")
    print(f"  HypatiaX   : mean={s['hybrid_all'][0]:.3f}s  median={s['hybrid_all'][1]:.3f}s  (n={s['n']})")
    print(f"  HypatiaX (LLM-routed only): mean={s['hybrid_llm_routed'][0]:.3f}s  "
          f"median={s['hybrid_llm_routed'][1]:.3f}s  (n={s['n_llm_routed']})")
    print()

    print("=== What the paper currently reports (runtime.tex / timing_detail.tex) ===")
    print(f"  Neural MLP : mean={REPORTED['nn'][0]}s  median={REPORTED['nn'][1]}s")
    print(f"  HypatiaX   : mean={REPORTED['hybrid_all'][0]}s  median={REPORTED['hybrid_all'][1]}s")
    print(f"  Reported headline: {REPORTED['hybrid_llm_routed_speedup_median']}")
    print()

    print("=== Discrepancy ===")
    nn_ratio = REPORTED["nn"][0] / s["nn"][0]
    print(f"  Reported Neural MLP mean is {nn_ratio:.1f}x the value this exact file actually contains.")
    hy_mean, hy_med = s["hybrid_all"]
    nn_mean, nn_med = s["nn"]
    print(f"  Real speedup, all 74 tasks: mean {hy_mean/nn_mean:.2f}x SLOWER, "
          f"median {hy_med/nn_med:.2f}x SLOWER (paper claims 2.30x slower mean / 1.64x FASTER median).")
    hyr_mean, hyr_med = s["hybrid_llm_routed"]
    print(f"  Real speedup, LLM-routed only (n={s['n_llm_routed']}): mean {hyr_mean/nn_mean:.2f}x SLOWER, "
          f"median {hyr_med/nn_med:.2f}x SLOWER (paper claims 1.73x FASTER).")
    print()
    print("  This independently confirms table1_audit_old.tex's finding (there: NN 0.36/0.36s,")
    print("  hybrid 4-9x slower across every reconstruction) using only the single file that")
    print("  runtime.tex/timing_detail.tex themselves already cite as their source -- i.e. this is")
    print("  not a different-seed or different-file ambiguity, it's the SAME file giving a")
    print("  different answer than what's printed in the paper's own 'auto-generated' tables.")
    print()

    corrected = generate_corrected_tex(s)

    print("=" * 78)
    print("FULL REPLACEMENT for tab:runtime (runtime.tex)")
    print("=" * 78)
    print()
    print("--- ORIGINAL (does not match its own cited source) ---")
    print(ORIGINAL_TEX_RUNTIME)
    print("--- REPLACEMENT (recomputed live from the cited source file) ---")
    print(corrected)

    with open("tab_runtime_corrected.tex", "w") as f:
        f.write(corrected)
    print("[Replacement written to tab_runtime_corrected.tex]")


if __name__ == "__main__":
    main()
